- hosts: elasticsearch_master_nodes
  roles:
    - role: elasticsearch
  vars:
    es_instance_name: "node1"
    es_heap_size: "6g"
    es_config:
      cluster.name: "hpc-analytics"
      discovery.zen.ping.unicast.hosts: ["adwnode34:9300", "adwnode35:9300", "adwnode36:9300"]
      http.port: 9200
      transport.tcp.port: 9300
      node.data: false
      node.master: true
      bootstrap.memory_lock: true
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_start_service: true

- hosts: elasticsearch_data_nodes
  roles:
    - role: elasticsearch
  vars:
    es_instance_name: "node1"
    es_heap_size: "24g"
    es_config:
      discovery.zen.ping.unicast.hosts: ["adwnode34:9300", "adwnode35:9300", "adwnode36:9300"]
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      node.master: false
      bootstrap.memory_lock: true
      cluster.name: "hpc-analytics"
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_start_service: true
