- hosts: elasticsearch_master_nodes
  roles:
    - role: elasticsearch
  vars:
    es_instance_name: "node1"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      discovery.zen.ping.unicast.hosts: "localhost:9300"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: false
      node.master: true
      bootstrap.memory_lock: true
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_start_service: true

