---

- hosts: es_master
#  user: siddis14
  become: yes
  become_method: sudo
  connection: ssh
  tasks:  
  - name: RedHat - add Elasticsearch repo
    template: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch-6.x.repo
    when: true

  - name: RedHat - Install Elasticsearch
    yum: pkg=elasticsearch  state=present update_cache=yes

  - name: Starting Elastic Search Service
    service: name=elasticsearch state=restarted 
