--- # Installing Packages Common to all hosts

- hosts: Andover
  connection: ssh
  sudo: yes
  gather_facts: no
  tasks:
  - name: Installing Packages
    yum: pkg={{ item }} state=present update_cache=yes
    with_items:
      - python
      - python-devel
      - gcc
      - gcc-c++
      - gcc-gfortran
    register: output
  - debug: var=output
    


