--- # Installing Packages Common to all hosts

- hosts: Andover
  connection: ssh
  sudo: yes
  gather_facts: no
  vars_files: 
  - common-packages.yml

  tasks:
  - name: Installing Packages
    yum: pkg={{ packages }} state=present update_cache=yes
    register: output
  - debug: var=output
    


